version: '4.2'

services:

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:?}
      MYSQL_DATABASE: ${DATABASE_NAME:?}
      MYSQL_USER: ${DATABASE_USER:?}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?}
    ports:
      - ${DATABASE_PORT:-3306}:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - "./data:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  data-collection:
    image: cloudformation/data-collection
    build:
      context: ./data-collection
    volumes:
      - ./data-collection/src/usage/logger/logs:/app/src/usage/logger/logs
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: ${DATABASE_NAME:?}
      DATABASE_USER: ${DATABASE_USER:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      DATABASE_PORT: 3306
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN:?}